namespace UnityAdditions
{
    /// <summary>
    /// Static base class for storing configuration data used by other classes and extensions
    /// </summary>
    public static class UnityAdditionSettings
    {
        /// <summary>
        /// Suppress all warnings that would be generated by methods upon incorrect input being provided. Use if your code is intentionally
        /// operating and the thrown warnings do not apply to you. NOTE: This can be done on a per-incovation basis as opposed to class-wide.
        /// </summary>
        public static bool SuppressWarnings { get; set; } = false;

        /// <summary>
        /// Suppress any error that is thrown because of bad input. NOT RECCOMMENDED
        /// </summary>
        public static bool SuppressErrors { get; set; } = false;

        /// <summary>
        /// NOT IMPLEMENTED
        /// Should all classes and extensions use the new (Unity.Mathematics) or the old (UnityEngine.Mathf) mathematic classes? NOTE: The new
        /// mathematics library is performance-focussed and is being built alongside the new Data-Oriented Technology Stack (DOTS). You must have
        /// the Mathematics package installed to use the new system
        /// </summary>
        public static bool UseMathematics { get; set; } = false;
    }
}