namespace UnityAdditions.Vector3
{
    using UnityEngine;

    /// <summary>
    /// Suite of extension methods for randomizing the x, y and z values of any vector 3
    /// </summary>
    public static class Vector3Extensions
    {
        /// <summary>
        /// Randomize the values of a vector using the provided input inclusively
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="posNegRange">Vector range between -x to x, -y to y, and -z to z</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void RandomizeValues(this ref Vector3 v, Vector3 posNegRange, bool suppressWarnings = false)
        {
            if (posNegRange == Vector3.zero)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with {posNegRange} whos value was Zero, no action was taken");
                return;
            }

            v.x = (posNegRange.x == 0) ? 0 : Random.Range(-posNegRange.x, posNegRange.x);
            v.y = (posNegRange.y == 0) ? 0 : Random.Range(-posNegRange.y, posNegRange.y);
            v.z = (posNegRange.z == 0) ? 0 : Random.Range(-posNegRange.z, posNegRange.z);
        }

        /// <summary>
        /// Randomize the values of a vector using the provided input inclusively
        /// </summary>
        /// <remarks>Method can error out</remarks>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="lowerBound">Lower bound for vector x, y and z values</param>
        /// <param name="upperBound">Upper bound for vector x, y and z values</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void RandomizeValues(this ref Vector3 v, Vector3 lowerBound, Vector3 upperBound, bool suppressWarnings = false)
        {
            if (lowerBound == upperBound)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with lowerBound:{lowerBound} and upperBound:{upperBound} whos values were equal, no action was taken");
                return;
            }
            if (upperBound.x < lowerBound.x || upperBound.y < lowerBound.y || upperBound.z < lowerBound.z)
            {
                if (!UnityAdditionSettings.SuppressErrors)
                    Debug.LogError($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with lowerBound:{lowerBound} who possessed a value greater than the corresponding value in upperBound:{upperBound}");
                return;
            }

            v.x = (lowerBound.x == upperBound.x) ? lowerBound.x : Random.Range(lowerBound.x, upperBound.x);
            v.y = (lowerBound.y == upperBound.y) ? lowerBound.y : Random.Range(lowerBound.y, upperBound.y);
            v.z = (lowerBound.z == upperBound.z) ? lowerBound.z : Random.Range(lowerBound.z, upperBound.z);
        }

        /// <summary>
        /// Randomize the values of a vector using the provided input inclusively. Will warn when all values passed are zero.
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="xRange">Range to randomize between -xRange and xRange. Ignored when value is zero</param>
        /// <param name="yRange">Range to randomize between -yRange and yRange. Ignored when value is zero</param>
        /// <param name="zRange">Range to randomize between -zRange and zRange. Ignored when value is zero</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void RandomizeValues(this ref Vector3 v, float xRange = 0f, float yRange = 0f, float zRange = 0f, bool suppressWarnings = false)
        {
            if (xRange == 0 && yRange == 0 && zRange == 0)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xRange:{xRange}, yRange:{yRange} and zRange:{zRange} whos values were Zero, no action was taken");
                return;
            }

            v.x = (xRange == 0) ? 0 : Random.Range(-xRange, xRange);
            v.y = (yRange == 0) ? 0 : Random.Range(-yRange, yRange);
            v.z = (zRange == 0) ? 0 : Random.Range(-zRange, zRange);
        }

        /// <summary>
        /// Randomize the values of a vector using the provided input inclusively. Will warn when all values passed are zero and
        /// will error if any value's upper bound is less than its corresponding lower bound and UnityExtensions.SuppressErrors is false.
        /// </summary>
        /// <remarks>Method can error out</remarks>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="xLower">Lower x value bound</param>
        /// <param name="xUpper">Upper x value bound</param>
        /// <param name="yLower">Lower y value bound</param>
        /// <param name="yUpper">Upper y value bound</param>
        /// <param name="zLower">Lower z value bound</param>
        /// <param name="zUpper">Upper z value bound</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void RandomizeValues(this ref Vector3 v, float xLower = 0f, float xUpper = 0f, float yLower = 0f, float yUpper = 0f, float zLower = 0f, float zUpper = 0f, bool suppressWarnings = false)
        {
            if (xLower == 0 && xUpper == 0 && yLower == 0 && yUpper == 0 && zLower == 0 && zUpper == 0)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xLower:{xLower}, xUpper:{xUpper}, yLower:{yLower}, yUpper:{yUpper}, zLower:{zLower} and zUpper:{zUpper} whos values were Zero, no action was taken");
                return;
            }

            if (xUpper < xLower || yUpper < yLower || zUpper < zLower)
            {
                if (!UnityAdditionSettings.SuppressErrors)
                    Debug.LogError($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xLower:{xLower}, yLower:{yLower}, and zLower:{zLower} who possessed a value greater than the corresponding value of xUpper:{xUpper}, yUpper{yUpper}, or zUpper{zUpper}");
                return;
            }

            v.x = (xLower == xUpper) ? xLower : Random.Range(xLower, xUpper);
            v.y = (yLower == yUpper) ? yLower : Random.Range(yLower, yUpper);
            v.z = (zLower == zUpper) ? zLower : Random.Range(zLower, zUpper);
        }

        /// <summary>
        /// Randomize the values of a vector within a provided boundary. NOTE: Provided coordinates will be in WORLD COORDINATES, as Bounds stores
        /// its coordinates as such.
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="randomizeInside">Boundary to keep the vector inside</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void RandomizeWithin(this ref Vector3 v, Bounds randomizeInside, bool suppressWarnings = false)
        {
            if (randomizeInside.size == Vector3.zero)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with {randomizeInside} whos size was Zero, no action was taken");
                return;
            }

            Vector3 min = randomizeInside.min, max = randomizeInside.max;
            v.x = (min.x == max.x) ? min.x : Random.Range(min.x, max.x);
            v.y = (min.y == max.y) ? min.y : Random.Range(min.y, max.y);
            v.z = (min.z == max.z) ? min.z : Random.Range(min.z, max.z);
        }

        /// <summary>
        /// Ensure a vector's individual values never become greater than 1 or less than 0
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        public static void ClampValues01(this ref Vector3 v)
        {
            v.x = (v.x < 0f) ? 0 : (v.x > 1f) ? 1 : v.x;
            v.y = (v.y < 0f) ? 0 : (v.y > 1f) ? 1 : v.y;
            v.z = (v.z < 0f) ? 0 : (v.z > 1f) ? 1 : v.z;
        }

        /// <summary>
        /// Ensure a vector's individual values never fall below zero
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        public static void ClampValuesPositive(this ref Vector3 v)
        {
            v.x = (v.x < 0f) ? 0 : v.x;
            v.y = (v.y < 0f) ? 0 : v.y;
            v.z = (v.z < 0f) ? 0 : v.z;
        }

        /// <summary>
        /// Ensure a vector's individial values never rise above zero
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        public static void ClampValuesNegative(this ref Vector3 v)
        {
            v.x = (v.x > 0f) ? 0 : v.x;
            v.y = (v.y > 0f) ? 0 : v.y;
            v.z = (v.y > 0f) ? 0 : v.z;
        }

        /// <summary>
        /// Clamp the individual values of a vector between the provided values
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="minMax">Vector clamp between -x to x, -y to y and -z to z</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void ClampValuesBetween(this ref Vector3 v, Vector3 minMax, bool suppressWarnings = false)
        {
            if (minMax == Vector3.zero)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(ClampValuesBetween)} was invoked with minMax:{minMax} whos value was Zero, no action was taken");
                return;
            }

            v.x = (v.x < -minMax.x) ? -minMax.x : (v.x > minMax.x) ? minMax.x : v.x;
            v.y = (v.y < -minMax.y) ? -minMax.y : (v.y > minMax.y) ? minMax.y : v.y;
            v.z = (v.z < -minMax.z) ? -minMax.z : (v.z > minMax.z) ? minMax.z : v.z;
        }

        /// <summary>
        /// Clamp the individual values of a vector between the provided values
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="min">Minimum clamp value for vector x, y and z</param>
        /// <param name="max">Maximum clamp value for vector x, y and z</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void ClampValuesBetween(this ref Vector3 v, Vector3 min, Vector3 max, bool suppressWarnings = false)
        {
            if (min == max)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(ClampValuesBetween)} was invoked with min:{min} and max:{max} whos values were equal, no action was taken");
                return;
            }

            if (max.x < min.x || max.y < min.y || max.z < min.z)
            {
                if (!UnityAdditionSettings.SuppressErrors)
                    Debug.LogError($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with min:{min} who possessed a value greater than the corresponding value in max:{max}");
                return;
            }

            v.x = (v.x < min.x) ? min.x : (v.x > max.x) ? max.x : v.x;
            v.y = (v.y < min.y) ? min.y : (v.y > max.y) ? max.y : v.y;
            v.z = (v.z < min.z) ? min.z : (v.z > max.z) ? max.z : v.z;
        }

        /// <summary>
        /// Clamp the individual values of a vector between the provided values
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="xMinMax">Range to randomize between -<paramref name="xMinMax"/> and <paramref name="xMinMax"/>. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="yMinMax">Range to randomize between -<paramref name="yMinMax"/> and <paramref name="yMinMax"/>. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="zMinMax">Range to randomize between -<paramref name="zMinMax"/> and <paramref name="zMinMax"/>. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="ignoreWhenZero">Should values clamp when respective range parameter is zero? False if corresponding values should always be zero</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void ClampValuesBetween(this ref Vector3 v, float xMinMax = 0f, float yMinMax = 0f, float zMinMax = 0f, bool ignoreWhenZero = true, bool suppressWarnings = false)
        {
            if (xMinMax == 0 && yMinMax == 0 && zMinMax == 0)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xMinMax:{xMinMax}, yMinMax:{yMinMax} and zMinMax:{zMinMax} whos values were Zero, no action was taken");
                return;
            }

            v.x = (xMinMax == 0) ? (ignoreWhenZero) ? v.x : 0 : (v.x < -xMinMax) ? -xMinMax : (v.x > xMinMax) ? xMinMax : v.x;
            v.y = (yMinMax == 0) ? (ignoreWhenZero) ? v.y : 0 : (v.y < -yMinMax) ? -yMinMax : (v.y > yMinMax) ? yMinMax : v.y;
            v.z = (zMinMax == 0) ? (ignoreWhenZero) ? v.z : 0 : (v.z < -zMinMax) ? -zMinMax : (v.z > zMinMax) ? zMinMax : v.z;
        }

        /// <summary>
        /// Clamp the individual values of a vector between the provided values
        /// </summary>
        /// <param name="v">Vector3 instance this method operates on</param>
        /// <param name="xMin">Lower x value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="xMax">Upper x value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="yMin">Lower y value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="yMax">Upper y value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="zMin">Lower z value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="zMax">Upper z value clamp. Zero behavior dependant on <paramref name="ignoreWhenZero"/> parameter</param>
        /// <param name="ignoreWhenZero">Should values clamp when respective range parameters are zero? False if corresponding values should always be zero</param>
        /// <param name="suppressWarnings">Suppress warnings which would otherwise be generated by this method</param>
        public static void ClampValuesBetween(this ref Vector3 v, float xMin = 0f, float xMax = 0f, float yMin = 0f, float yMax = 0f, float zMin = 0f, float zMax = 0f, bool ignoreWhenZero = true, bool suppressWarnings = false)
        {
            if (xMin == xMax && yMin == yMax && zMin == zMax)
            {
                if (!suppressWarnings || !UnityAdditionSettings.SuppressWarnings)
                    Debug.LogWarning($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xMin:{xMin}, xMax:{xMax}, yMin:{yMin}, yMax:{yMax}, zMin:{zMin} and zMax:{zMax} whos values were Zero, no action was taken");
                return;
            }

            if (xMax < xMin || yMax < yMin || zMax < zMin)
            {
                if (UnityAdditionSettings.SuppressErrors)
                    Debug.LogError($"{nameof(Vector3Extensions)}.{nameof(RandomizeValues)} was invoked with xMin:{xMin}, yMin:{yMin}, and zMin:{zMin} who possessed a value greater than the corresponding value of xMax:{xMax}, yMax:{yMax}, or zMax:{zMax}");
                return;
            }

            v.x = (xMin == xMax) ? (xMin == 0) ? (ignoreWhenZero) ? v.x : 0 : xMin : (v.x < xMin) ? xMin : (v.x > xMax) ? xMax : v.x;
            v.y = (yMin == yMax) ? (yMin == 0) ? (ignoreWhenZero) ? v.y : 0 : yMin : (v.y < yMin) ? yMin : (v.y > yMax) ? yMax : v.y;
            v.z = (zMin == zMax) ? (zMin == 0) ? (ignoreWhenZero) ? v.z : 0 : zMin : (v.z < zMin) ? zMin : (v.z > zMax) ? zMax : v.z;
        }
    }
}